version: '3'

services:
  database:
    image: 'postgres:15'
    ports:
      - "5435:5432"
    environment:
      - .env
    networks:
      - postgres-network
    volumes:
      - /opt/db:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - "5051:5051"
    environment:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - /opt/dev/pgadmin:/var/lib/pgadmin/

networks: 
  postgres-network:
    driver: bridge
